// Инициализируем начальные данные игроков
window.initialPlayers = [
  { 
    nick: 'ЦАРЬ', 
    maxLevel: '12', 
    withGreat: '+', 
    role: 'Лидер', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '20:00-23:00', 
    class: 'Воин', 
    telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Марс', 
    maxLevel: 'от 9?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '19:00-22:00', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'AND-XXX', 
    maxLevel: 'от 11?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Respect J.J.', 
    maxLevel: '12', 
    withGreat: '-', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Тупо Бот', 
    maxLevel: '10', 
    withGreat: '-', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Kring12', 
    maxLevel: '13.12', 
    withGreat: '+', 
    role: 'Офицер', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'юра', 
    maxLevel: '10?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Integra', 
    maxLevel: '11?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'ABAKAN', 
    maxLevel: '11?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'ALEX', 
    maxLevel: '11?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Tausida', 
    maxLevel: '13.12', 
    withGreat: '+', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Гала', 
    maxLevel: '10?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Neomaster', 
    maxLevel: '12?', 
    withGreat: '-', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Январь', 
    maxLevel: '13.12', 
    withGreat: '+', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Team Raymond', 
    maxLevel: '?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Team A', 
    maxLevel: '13.12', 
    withGreat: '+', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Галахад', 
    maxLevel: '13.12', 
    withGreat: '+?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'DaHyHax', 
    maxLevel: '13.12', 
    withGreat: '+', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Kagakora', 
    maxLevel: '13.12', 
    withGreat: '+', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'FamilyWarriors', 
    maxLevel: '?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Перфекционист', 
    maxLevel: '13.12', 
    withGreat: '+', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Blagodatnyj', 
    maxLevel: '?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Олег', 
    maxLevel: '10?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'тан сан', 
    maxLevel: '?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Pulpo', 
    maxLevel: '?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Skit Skit Bang', 
    maxLevel: '?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  },
  { 
    nick: 'Team HICHBLACK', 
    maxLevel: '?', 
    withGreat: '?', 
    role: 'Участник', 
    status: 'Активен', 
    timezone: 'Москва', 
    activeHours: '?', 
    class: '?', 
     telegram: '@tsar_username', 
    comment: '' 
  }
];
// Этот файл теперь содержит только начальные данные
// Вся логика работы с таблицей перенесена в script.js